import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'pt-BR' | 'en' | 'de' | 'fr';

const translations: Record<Lang, Record<string, string>> = {
  'pt-BR': {
    // Header
    'header.search': 'O que você procura?',
    'header.categories': 'Categorias',
    'header.cart': 'Carrinho',
    'header.account': 'Conta',
    'header.login': 'Entrar',
    'header.delivery': 'Entrega para toda a cidade',
    'header.free_shipping': 'Frete grátis acima de R$99',
    'header.all': 'Todos',
    // Home
    'home.hero_title': 'Descubra o melhor da sua cidade',
    'home.hero_subtitle': 'Compre online de lojas locais com entrega rápida ou retire na loja',
    'home.shop_now': 'Explorar Produtos',
    'home.categories': 'Categorias',
    'home.featured': 'Destaques',
    'home.promos': 'Promoções',
    'home.new': 'Novidades',
    'home.stores': 'Lojas Participantes',
    'home.benefits_title': 'Por que comprar local?',
    'home.benefit_1': 'Entrega rápida',
    'home.benefit_1_desc': 'Receba no mesmo dia ou retire na loja',
    'home.benefit_2': 'Apoie o comércio local',
    'home.benefit_2_desc': 'Fortaleça a economia da sua cidade',
    'home.benefit_3': 'Pagamento seguro',
    'home.benefit_3_desc': 'Pix e cartão com total segurança',
    'home.benefit_4': 'Atendimento próximo',
    'home.benefit_4_desc': 'Fale direto com o lojista',
    // Product
    'product.add_cart': 'Adicionar ao Carrinho',
    'product.in_stock': 'Em estoque',
    'product.out_stock': 'Esgotado',
    'product.delivery': 'Entrega disponível',
    'product.pickup': 'Retirada na loja',
    'product.related': 'Produtos Relacionados',
    'product.store': 'Vendido por',
    // Cart
    'cart.title': 'Carrinho',
    'cart.empty': 'Seu carrinho está vazio',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.checkout': 'Finalizar Compra',
    'cart.continue': 'Continuar Comprando',
    // Footer
    'footer.about': 'Sobre',
    'footer.help': 'Ajuda',
    'footer.terms': 'Termos',
    'footer.privacy': 'Privacidade',
    // Auth
    'auth.login': 'Entrar',
    'auth.signup': 'Criar Conta',
    'auth.google': 'Continuar com Google',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.name': 'Nome completo',
    'auth.no_account': 'Não tem conta?',
    'auth.has_account': 'Já tem conta?',
    'auth.login_subtitle': 'Acesse sua conta para continuar comprando',
    'auth.signup_subtitle': 'Crie sua conta e comece a comprar',
    // General
    'general.loading': 'Carregando...',
    'general.save': 'Salvar',
    'general.cancel': 'Cancelar',
    'general.delete': 'Excluir',
    'general.edit': 'Editar',
    'general.view_all': 'Ver todos',
    'general.filter': 'Filtrar',
    'general.sort': 'Ordenar',
    'general.price': 'Preço',
    'general.off': 'OFF',
  },
  en: {
    'header.search': 'What are you looking for?',
    'header.categories': 'Categories',
    'header.cart': 'Cart',
    'header.account': 'Account',
    'header.login': 'Sign In',
    'header.delivery': 'Delivery across the city',
    'header.free_shipping': 'Free shipping over R$99',
    'header.all': 'All',
    'home.hero_title': 'Discover the best of your city',
    'home.hero_subtitle': 'Shop online from local stores with fast delivery or in-store pickup',
    'home.shop_now': 'Explore Products',
    'home.categories': 'Categories',
    'home.featured': 'Featured',
    'home.promos': 'Deals',
    'home.new': 'New Arrivals',
    'home.stores': 'Participating Stores',
    'home.benefits_title': 'Why buy local?',
    'home.benefit_1': 'Fast delivery',
    'home.benefit_1_desc': 'Same-day delivery or in-store pickup',
    'home.benefit_2': 'Support local commerce',
    'home.benefit_2_desc': 'Strengthen your city\'s economy',
    'home.benefit_3': 'Secure payment',
    'home.benefit_3_desc': 'Pix and card with total security',
    'home.benefit_4': 'Close support',
    'home.benefit_4_desc': 'Talk directly to the seller',
    'product.add_cart': 'Add to Cart',
    'product.in_stock': 'In stock',
    'product.out_stock': 'Out of stock',
    'product.delivery': 'Delivery available',
    'product.pickup': 'In-store pickup',
    'product.related': 'Related Products',
    'product.store': 'Sold by',
    'cart.title': 'Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.continue': 'Continue Shopping',
    'footer.about': 'About',
    'footer.help': 'Help',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'auth.login': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.google': 'Continue with Google',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full name',
    'auth.no_account': "Don't have an account?",
    'auth.has_account': 'Already have an account?',
    'auth.login_subtitle': 'Access your account to continue shopping',
    'auth.signup_subtitle': 'Create your account and start shopping',
    'general.loading': 'Loading...',
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    'general.delete': 'Delete',
    'general.edit': 'Edit',
    'general.view_all': 'View all',
    'general.filter': 'Filter',
    'general.sort': 'Sort',
    'general.price': 'Price',
    'general.off': 'OFF',
  },
  de: {
    'header.search': 'Wonach suchen Sie?',
    'header.categories': 'Kategorien',
    'header.cart': 'Warenkorb',
    'header.account': 'Konto',
    'header.login': 'Anmelden',
    'header.delivery': 'Lieferung in der ganzen Stadt',
    'header.free_shipping': 'Kostenloser Versand ab R$99',
    'header.all': 'Alle',
    'home.hero_title': 'Entdecken Sie das Beste Ihrer Stadt',
    'home.hero_subtitle': 'Online einkaufen bei lokalen Geschäften mit schneller Lieferung oder Abholung',
    'home.shop_now': 'Produkte Entdecken',
    'home.categories': 'Kategorien',
    'home.featured': 'Highlights',
    'home.promos': 'Angebote',
    'home.new': 'Neuheiten',
    'home.stores': 'Teilnehmende Geschäfte',
    'home.benefits_title': 'Warum lokal kaufen?',
    'home.benefit_1': 'Schnelle Lieferung',
    'home.benefit_1_desc': 'Am selben Tag geliefert oder im Geschäft abholen',
    'home.benefit_2': 'Lokalen Handel unterstützen',
    'home.benefit_2_desc': 'Stärken Sie die Wirtschaft Ihrer Stadt',
    'home.benefit_3': 'Sichere Zahlung',
    'home.benefit_3_desc': 'Pix und Karte mit voller Sicherheit',
    'home.benefit_4': 'Persönlicher Support',
    'home.benefit_4_desc': 'Sprechen Sie direkt mit dem Händler',
    'product.add_cart': 'In den Warenkorb',
    'product.in_stock': 'Auf Lager',
    'product.out_stock': 'Ausverkauft',
    'product.delivery': 'Lieferung verfügbar',
    'product.pickup': 'Abholung im Geschäft',
    'product.related': 'Ähnliche Produkte',
    'product.store': 'Verkauft von',
    'cart.title': 'Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.subtotal': 'Zwischensumme',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    'cart.continue': 'Weiter Einkaufen',
    'footer.about': 'Über uns',
    'footer.help': 'Hilfe',
    'footer.terms': 'AGB',
    'footer.privacy': 'Datenschutz',
    'auth.login': 'Anmelden',
    'auth.signup': 'Konto erstellen',
    'auth.google': 'Weiter mit Google',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.name': 'Vollständiger Name',
    'auth.no_account': 'Noch kein Konto?',
    'auth.has_account': 'Bereits ein Konto?',
    'auth.login_subtitle': 'Melden Sie sich an, um weiter einzukaufen',
    'auth.signup_subtitle': 'Erstellen Sie Ihr Konto und kaufen Sie ein',
    'general.loading': 'Laden...',
    'general.save': 'Speichern',
    'general.cancel': 'Abbrechen',
    'general.delete': 'Löschen',
    'general.edit': 'Bearbeiten',
    'general.view_all': 'Alle anzeigen',
    'general.filter': 'Filter',
    'general.sort': 'Sortieren',
    'general.price': 'Preis',
    'general.off': 'RABATT',
  },
  fr: {
    'header.search': 'Que cherchez-vous ?',
    'header.categories': 'Catégories',
    'header.cart': 'Panier',
    'header.account': 'Compte',
    'header.login': 'Connexion',
    'header.delivery': 'Livraison dans toute la ville',
    'header.free_shipping': 'Livraison gratuite dès R$99',
    'header.all': 'Tous',
    'home.hero_title': 'Découvrez le meilleur de votre ville',
    'home.hero_subtitle': 'Achetez en ligne dans les boutiques locales avec livraison rapide ou retrait en magasin',
    'home.shop_now': 'Explorer les Produits',
    'home.categories': 'Catégories',
    'home.featured': 'En vedette',
    'home.promos': 'Promotions',
    'home.new': 'Nouveautés',
    'home.stores': 'Boutiques Participantes',
    'home.benefits_title': 'Pourquoi acheter local ?',
    'home.benefit_1': 'Livraison rapide',
    'home.benefit_1_desc': 'Livré le jour même ou retrait en magasin',
    'home.benefit_2': 'Soutenir le commerce local',
    'home.benefit_2_desc': 'Renforcez l\'économie de votre ville',
    'home.benefit_3': 'Paiement sécurisé',
    'home.benefit_3_desc': 'Pix et carte en toute sécurité',
    'home.benefit_4': 'Support de proximité',
    'home.benefit_4_desc': 'Parlez directement au vendeur',
    'product.add_cart': 'Ajouter au Panier',
    'product.in_stock': 'En stock',
    'product.out_stock': 'Épuisé',
    'product.delivery': 'Livraison disponible',
    'product.pickup': 'Retrait en magasin',
    'product.related': 'Produits Similaires',
    'product.store': 'Vendu par',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.subtotal': 'Sous-total',
    'cart.total': 'Total',
    'cart.checkout': 'Commander',
    'cart.continue': 'Continuer vos achats',
    'footer.about': 'À propos',
    'footer.help': 'Aide',
    'footer.terms': 'Conditions',
    'footer.privacy': 'Confidentialité',
    'auth.login': 'Connexion',
    'auth.signup': 'Créer un Compte',
    'auth.google': 'Continuer avec Google',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'auth.name': 'Nom complet',
    'auth.no_account': "Pas de compte ?",
    'auth.has_account': 'Déjà un compte ?',
    'auth.login_subtitle': 'Connectez-vous pour continuer vos achats',
    'auth.signup_subtitle': 'Créez votre compte et commencez à acheter',
    'general.loading': 'Chargement...',
    'general.save': 'Enregistrer',
    'general.cancel': 'Annuler',
    'general.delete': 'Supprimer',
    'general.edit': 'Modifier',
    'general.view_all': 'Voir tout',
    'general.filter': 'Filtrer',
    'general.sort': 'Trier',
    'general.price': 'Prix',
    'general.off': 'RÉDUCTION',
  },
};

const langLabels: Record<Lang, string> = {
  'pt-BR': '🇧🇷 Português',
  en: '🇺🇸 English',
  de: '🇩🇪 Deutsch',
  fr: '🇫🇷 Français',
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  langs: { value: Lang; label: string }[];
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'pt-BR',
  setLang: () => {},
  t: (k) => k,
  langs: [],
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const saved = localStorage.getItem('app-lang');
      if (saved && ['pt-BR', 'en', 'de', 'fr'].includes(saved)) return saved as Lang;
    } catch {}
    return 'pt-BR';
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem('app-lang', l); } catch {}
  };

  const t = (key: string) => translations[lang]?.[key] || translations['pt-BR']?.[key] || key;

  const langs = (Object.keys(langLabels) as Lang[]).map(v => ({ value: v, label: langLabels[v] }));

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, langs }}>
      {children}
    </LanguageContext.Provider>
  );
};
